services:

  # Postgresql
  postgres:
    image: postgres:15
    container_name: youapp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5448:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


  # Redis service
  redis:
    image: redis:6-alpine
    container_name: youapp-redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data


volumes:
  pgdata:
  redis_data:

networks:
  backend:

name: YouApp